# CI on Push
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo current time
        run: echo "The current server time is $(date)"
        